### ISSUE TITLE
v1.0.1 massively bloated the size of this package via dependencies

### ISSUE THREAD

**Issue by domenic** [ljharb/listify#9]
Take a look at the lockfile change in https://github.com/whatwg/participate.whatwg.org/pull/104. Going from v1.0.0 to v1.0.1 added the following dependencies to my project:

- define-properties
- es-abstract
- es-to-primitive
- function-bind
- has
- has-symbols
- is-callable
- is-date-object
- is-regex
- is-symbol
- object-inspect
- object-keys
- object.assign
- string.prototype.trim
- string.prototype.trimend
- string.prototype.trimleft
- string.prototype.trimright
- string.prototype.trimstart

This isn't really acceptable for a listification package.

Would it be possible to revert whatever caused this? The [changelog](https://github.com/ljharb/listify/blob/master/CHANGELOG.md#v101---2020-04-12) is rather noisy so I can't figure out what it was...

**Comment by ljharb** [comment]
In general, "what dependencies it uses" isn't something that one should have expectations on in either direction; a patch could add a thousand, or none, and that's fine.

In this case, it's likely mostly due to https://github.com/ljharb/listify/blob/master/index.js#L4, added in https://github.com/ljharb/listify/commit/f645b490bb5e223c567acf102fb9ae87f2b5e6c6 - this package supports environments where `.trim()` may not be available.

**Comment by domenic** [comment]
It's not fine for my purposes; increasing the size of my dependency graph when trying to listify values is not acceptable.

Do you have an intention to fix this, or does your philosophy prevent doing so?

**Comment by domenic** [comment]
Going from [582 bytes](https://bundlephobia.com/result?p=listify@1.0.0) to [13.6 kB](https://bundlephobia.com/result?p=listify@1.0.1) is, in particular, not a regression I'm able to take on in my project.

**Comment by ljharb** [comment]
I think typically, it would; but since v1.0.0 has, for years, relied on `.trim()` being available, it's reasonable to revert that commit in a v1.0.2.

**Comment by ljharb** [comment]
v1.0.2 is released.

**Comment by domenic** [comment]
Thanks very much! However, 1.0.2 still contains the rather-large `function-bind` package, plus the not-as-large `has` package: https://bundlephobia.com/result?p=listify@1.0.2 .

Is it possible to just get a no-dependency package that listifies? It'd be a shame to have to write that myself...

**Comment by ljharb** [comment]
It does use `has` (which in turn uses `function-bind`); i'm actually surprised it's not already in your graph, as it's very widely used.

You wouldn't need to write it yourself; you'd just pin to v1.0.0 of listify and everything would be fine. The only functionality added after v1.0.0 was "using `has`, and using `string.prototype.trim`"; if i removed `has` then v1.0.3 would be identical to v1.0.0, and I'm not sure why that's preferable to pinning to v1.0.0?

**Comment by domenic** [comment]
I'd rather use a package which I can rely on the latest version being suitable for my needs, than pin an old version. It looks like there are a number of alternatives though: https://www.npmjs.com/search?q=list%20comma

I agree that 1.0.0 was a better package than 1.0.1 or 1.0.2.

**Comment by wincent** [comment]
@domenic:

> It'd be a shame to have to write that myself...

At the same time, if you did write it yourself, you'd never have to worry about the dependency graph changing in unexpected or undesirable ways again; something that is not merely a hypothetical concern when the maintainer of `listify` holds a philosophy about dependencies so very obviously different from your own; ie:

> "what dependencies it uses" isn't something that one should have expectations on in either direction; a patch could add a thousand, or none, and that's fine.

Costs of "reinventing the wheel":

- Your reimplementation might be buggy.
- Some other dependency in your graph might continue to pull down this or some subset of its graph anyway, so you'd wind up with duplicate/redundant code.

Benefits:

- You isolate yourself from all of the liabilities that come with a dependency graph that you don't fully control (among other things, potential bloat, greater surface area to audit for security problems, licensing complications, changes in funding model etc).

For a straightforward, [30-line implementation like this one](https://github.com/ljharb/listify/blob/984acd129e8b8e52458a45b86fa168815f33b8f3/index.js), you'd have to decide if the cost of maintaining a local equivalent is trivial compared to the potential downsides of continued reuse.

`listify` could easily be a dependency-free package, but it's not, because the maintainer [would rather write](https://github.com/ljharb/listify/blob/984acd129e8b8e52458a45b86fa168815f33b8f3/index.js#L14-L15):

```js
var separator = has(options, 'separator') ? options.separator : ', ';
var finalWord = has(options, 'finalWord') ? options.finalWord : 'and';
```

than an alternative like:

```js
var separator = options.separator == undefined ? ', ' : options.separator;
var finalWord = options.finalWord == undefined ? 'and' : options.finalWord;
```
or:

```js
var separator = options.separator === void 0 ? ', ' : options.separator;
var finalWord = options.finalWord === void 0 ? 'and' : options.finalWord;
```

or:

```js
var separator = typeof options.separator === 'string' ? options.separator : ', ';
var finalWord = typeof options.finalWord === 'string' ? options.finalWord : 'and';
```

or:

```js
var separator = Object.prototype.hasOwnProperty.call(options, 'separator') ? options.separator : ', ';
var finalWord = Object.prototype.hasOwnProperty.call(options, 'finalWord') ? options.finalWord : 'and';
```

etc. (needless to say, I am aware the each implementation has its subtleties; just throwing them out there by way of examples; you could pick one and tweak in various ways).

The consequence of that choice is that we involve `has`,  which is [a 1-line package](https://github.com/tarruda/has/blob/8146666148f1812f90e737aeefcded17a8cf81f4/src/index.js#L5) that does:

```js
module.exports = bind.call(Function.call, Object.prototype.hasOwnProperty);
```

which in turn uses `function-bind`, another [basically 1-line package](https://github.com/Raynos/function-bind/blob/1fe8f6e9aed0dfa8d8b3cdbd00c7f5ea0cd2b36e/index.js#L5):

```js
module.exports = Function.prototype.bind || implementation;
```

`implementation` is a [50-line fallback](https://github.com/Raynos/function-bind/blob/1fe8f6e9aed0dfa8d8b3cdbd00c7f5ea0cd2b36e/implementation.js) that is very unlikely to be used by any codebase using `listify`, because `listify` already [uses `Array.isArray`](https://github.com/ljharb/listify/blob/984acd129e8b8e52458a45b86fa168815f33b8f3/index.js#L6), and [as far as I can tell](http://kangax.github.io/compat-table/es5/), any engine that implements that is *also* going to provide `Function.prototype.bind`. You *could* posit a strange scenario in why somebody is using `listify` in an old engine and has polyfilled `Array.isArray` but not `Function.prototype.bind`, but the odds of that seem vanishingly small, and writing this without `Function.prototype.bind` seems not only easy, but more desirable in terms of obviousness and readability. I personally would rather have a dumb, explicit ternary.

**Comment by ljharb** [comment]
That’s a fair point that listify already assumes es5; i can thus rely on .bind being present and inline the `has` dependency.

**Comment by ljharb** [comment]
v1.0.3 is released, with no dependencies.
